// <auto-generated />
namespace Liga_Futebol.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddArtilheiro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddArtilheiro));
        
        string IMigrationMetadata.Id
        {
            get { return "202504190233304_AddArtilheiro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
